<?php
$this->title = 'Mes Albums';
$this->headTitle($this->title);

//Session 
$mysession = new Zend_Session_Namespace('mysession');

if (!isset($mysession->counter)) {
    $mysession->counter = 1000;
} else {
    $mysession->counter++;
}

if ($mysession->counter > 1999) {
    unset($mysession->counter);
}
echo $mysession->counter;
//#end test sessions
?>
<a href="<?php echo $this->url(array('controller'=>'auth', 'action'=>'login'));?>">login</a>
<p><a href="<?php echo $this->url(array('controller'=>'index','action'=>'ajouter'));?>">Ajouter de nouveaux albums</a></p>
<table>
    <tr>
        <th>Titre</th>
        <th>Artiste</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach($this->albums as $album) : ?>
        <tr>
            <td><?php echo $this->escape($album->titre);?></td>
            <td><?php echo $this->escape($album->artiste);?></td>
            <td>
                <a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'modifier', 'id'=>$album->id));?>">Modifier</a>
                <a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'supprimer', 'id'=>$album->id));?>">Supprimer</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>