<div>
    <table border="1">
        <tr>
            <th>id</th>
            <th>first name</th>
            <th>last name</th>
            <th>mail</th>
            <th>username</th>
            <th>role</th>
            <th>password</th>
        </tr>
        <?php
            //echo '<pre>', print_r($this->usersArray, 1), '</pre>';
        
            //$this->usersArray est une variable qui peut être garnie par le controller
            //elle doit recevoir un tableau contenant des objets de type Default_Model_Users
            //le tableau est parcouru par foreach et affiche les propiétés des objets contenus dans le tableau
            foreach ($this->usersArray as $users) :
        ?>
        <tr>
            <td><?php echo $users->id; ?></td>
            <td><?php echo $users->firstname; ?></td>
            <td><?php echo $users->lastname; ?></td>
            <td><?php echo $users->mail; ?></td>
            <td><?php echo $users->username; ?></td>
            <td><?php echo $users->role; ?></td>
            <td><?php echo $users->password; ?></td>
            <td>
                <a href="<?= $this->url(array('controller' => 'users', 'action' => 'edit', 'id' => $users->id), 'default', true); ?>">Edit</a>
            </td>
           <td>
                <a href="<?= $this->url(array('controller' => 'users', 'action' => 'delete', 'id' => $users->id), 'default', true); ?>">Delete</a>
            </td>
        </tr>
        <?php endforeach;?>
    </table>
</div>
