<?php
echo $this->doctype();
//DEPLACEMENT VERS BOOTSTRAP.PHP : la section d'initialisation des meta etc.. dans le bootstrap.php, ça regle les problemes notés @FLAG

/*$this->headMeta()->appendHttpEquiv('X-UA-Compatible', 'IE=edge,chrome=1');
$this->headMeta()->appendName('keywords', 'framework, PHP, productivité');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Tutoriel Zend Framework');*/
//@FLAG = pour que ça ne plante pas et que j'ai bien un encodage utf-8 en html5 je dois faire mon setCharset après echo $this->doctype('HTML5');, etrange non?
// début de réponse, si je place dans application.ini le resources.view.doctype = "HTML5" alors je peux placer echo $this->doctype(); à la fin, mais sans HTML5 en argument
//$this->headMeta()->setCharset('UTF-8'); // Will look like <meta charset="UTF-8">

//#END DEPLACEMENT VERS BOOTSTRAP.PHP 
?>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    
    <?php
    //Affichage des meta et du title chargé dans le bootstrap
    echo $this->headMeta();
    echo $this->headTitle();
    
    //Chargement du bootstrap.css dans l'aide de vue headlink
    $this->headLink()->prependStylesheet($this->baseUrl().'/css/bootstrap.min.css');
    //affichage style bootstrap.min.css
    echo $this->headLink();
    //Vidange du headLink
    $this->headLink()->exchangeArray(array());
    ?>
    <style>
        body {
            padding-top: 60px;
            padding-bottom: 40px;
        }
    </style>
    <?php
    //Chargement du bootstrap-responsive.css et du main.css dans l'aide de vue headlink
    $this->headLink()->prependStylesheet($this->baseUrl().'/css/main.css');
    $this->headLink()->prependStylesheet($this->baseUrl().'/css/bootstrap-responsive.min.css');
    //affichage
    echo $this->headLink(); 

    //Chargement de Modernizr, affichage et vidange de l'aide de vue headScript
    $this->headScript()->prependFile($this->baseUrl().'js/vendor/modernizr-2.6.2-respond-1.1.0.min.js');
    echo $this->headScript();
    $this->headScript()->exchangeArray(array());

    //Chargement de jQuery, bootstrap.js, plugin.js, et de main.js de l'aide de vue headScript
    $this->headScript()->appendFile('http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js');
    $this->headScript()->appendFile($this->baseUrl().'js/vendor/bootstrap.min.js');
    $this->headScript()->appendFile($this->baseUrl().'/js/plugins.js');
    $this->headScript()->appendFile($this->baseUrl().'/js/main.js');
    ?>   
</head>
<body>
    <!--[if lt IE 7]>
    <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <a class="brand" href="http://tutozf.localhost">Tuto ZF1</a>
                <div class="nav-collapse collapse">
                    <ul class="nav">
                        <li class="active"><a href="#">Home</a></li>
                        <li><a href="#about">About</a></li>
                        <li><a href="/users">users</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li class="divider"></li>
                                <li class="nav-header">Nav header</li>
                                <li><a href="#">Separated link</a></li>
                                <li><a href="#">One more separated link</a></li>
                            </ul>
                        </li>
                    </ul>
                    <form class="navbar-form pull-right">
                        <input class="span2" type="text" placeholder="Email">
                        <input class="span2" type="password" placeholder="Password">
                        <button type="submit" class="btn">Sign in</button>
                    </form>
                </div><!--/.nav-collapse -->
            </div>
        </div>
    </div>    
    <div class="container">
        <div class="header"> 
            <div id="logged-in-as">
                <?php echo $this->loggedInAs(); ?>
            </div>
        </div>
        
        <hr>
        
        <div class="hero-unit">
            <h1><?php echo $this->escape($this->title); ?></h1>
            <?php echo $this->layout()->content; ?>
        </div>
        
        <hr>
        
        <footer>
            <p>&copy; Company 2012</p>
        </footer>
    </div>

    <!-- SCRIPT JS  -->
    
    <?php 
    //affichage du contenu du headScript dans le footer
    echo $this->headScript(); ?>
    <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
    <script>
        //var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
        //(function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
        //g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
        //s.parentNode.insertBefore(g,s)}(document,'script'));
    </script>
</body>
</html>
