<?php
echo $this->doctype();
//DEPLACEMENT VERS BOOTSTRAP.PHP : la section d'initialisation des meta etc.. dans le bootstrap.php, ça regle les problemes notés @FLAG

/*$this->headMeta()->appendHttpEquiv('X-UA-Compatible', 'IE=edge,chrome=1');
$this->headMeta()->appendName('keywords', 'framework, PHP, productivité');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Tutoriel Zend Framework');*/
//@FLAG = pour que ça ne plante pas et que j'ai bien un encodage utf-8 en html5 je dois faire mon setCharset après echo $this->doctype('HTML5');, etrange non?
// début de réponse, si je place dans application.ini le resources.view.doctype = "HTML5" alors je peux placer echo $this->doctype(); à la fin, mais sans HTML5 en argument
//$this->headMeta()->setCharset('UTF-8'); // Will look like <meta charset="UTF-8">

//#END DEPLACEMENT VERS BOOTSTRAP.PHP 
?>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
        <?php $this->headLink()->prependStylesheet($this->baseUrl().'/css/main.css'); ?>
    <?php $this->headLink()->prependStylesheet($this->baseUrl().'/css/normalize.css'); ?>

   
    <?php echo $this->headLink(); ?>
</head>
<body>
    <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->
    <div id="content">
        <h1><?php echo $this->escape($this->title); ?></h1>
        <?php echo $this->layout()->content; ?>
    </div>
    
    <!-- SCRIPT JS  -->
    <?php
    //jQuery
    echo $this->headScript()->appendFile('http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js');
    //Modernizr
    echo $this->headScript()->appendFile($this->baseUrl().'/js/vendor/modernizr-2.6.2.min.js');
    echo $this->headScript()->appendFile($this->baseUrl().'/js/plugins.js');
    echo $this->headScript()->appendFile($this->baseUrl().'/js/main.js');
    
    ?>
    
    <!-- <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script> -->
    <!--<script>window.jQuery || document.write('<script src="../js/vendor/jquery-1.8.2.min.js"><\/script>')</script>-->
    <!-- <script src="../js/plugins.js"></script>
    <script src="../js/main.js"></script> -->
    <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
    <script>
        var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
        (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
        g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
        s.parentNode.insertBefore(g,s)}(document,'script'));
    </script>
    <!-- Modernizr -->
    <?php ?>
</body>
</html>
<?php ?>