<?php
$this->headMeta()->appendHttpEquiv('X-UA-Compatible', 'IE=edge,chrome=1');
$this->headMeta()->appendName('keywords', 'framework, PHP, productivité');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Tutoriel Zend Framework');
//@FLAG = pour que ça ne plante pas et que j'ai bien un encodage utf-8 en html5 je dois faire mon setCharset après echo $this->doctype('HTML5');, etrange non?
// début de réponse, si je place dans application.ini le resources.view.doctype = "HTML5" alors je peux placer echo $this->doctype(); à la fin, mais sans HTML5 en argument
$this->headMeta()->setCharset('UTF-8'); // Will look like <meta charset="UTF-8">
echo $this->doctype();
?>

<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
</head>
<body>
    <div id="content">
        <h1><?php echo $this->escape($this->title); ?></h1>
        <?php echo $this->layout()->content; ?>
    </div>
</body>
</html>
<?php ?>